title: hari
description: lah
template:
  repo: hari-template
  name: hari
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: createFile
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
      - type: deleteBranch

      print('hi')

      
